version: '3.8'

services:

  # Frontend website
  frontend:
    container_name: frontend
    build: ./
    command: npm run start
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    restart: unless-stopped

  # Backend API
  api:
    container_name: backend
    build: ./API
    command: npm start
    working_dir: /api
    ports:
      - "4000:4000"
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
    depends_on:
      - postgres
    volumes:
      - ./API:/api
    restart: unless-stopped

  # Postgres
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
